name: parkme
description: Your parking partner

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  google_maps_flutter: ^0.5.28+1
  splashscreen:
  geolocator: ^5.3.1
  google_sign_in: ^4.5.3
  qr_flutter:
  cloud_firestore: ^0.14.4
  razorpay_flutter: ^1.2.2
  fluttertoast: ^3.1.0
  carousel_slider: ^4.0.0
  twilio_flutter:

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  flutter_launcher_name: "^0.0.1"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/parkmeIcon.png"

flutter_launcher_name:
  name: "Park ME"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
